name: Test Workflow

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "utahiro-calendar"
          service_account: google-calendar-api@utahiro-calendar.iam.gserviceaccount.com
          workload_identity_provider: "projects/306157530435/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/calendar"
          create_credentials_file: true

      - name: Define variables
        run: |
          mv "$GOOGLE_GHA_CREDS_PATH" credentials.json
          cat << EOF > .env
          USER_AGENT="$USER_AGENT"
          EVENT_TITLE="$EVENT_TITLE"
          CALENDAR_ID="$CALENDAR_ID"
          PAGE_URL="$PAGE_URL"
          GOOGLE_GHA_CREDS_PATH=credentials.json
          EOF
        env:
          USER_AGENT: ${{ vars.USER_AGENT }}
          EVENT_TITLE: ${{ vars.EVENT_TITLE }}
          CALENDAR_ID: ${{ vars.CALENDAR_ID }}
          PAGE_URL: ${{ secrets.PAGE_URL }}
          GOOGLE_GHA_CREDS_PATH: ${{ steps.auth.outputs.credentials_file_path }}
    
      - run: docker compose build test
      - run: docker compose run test
